### ISSUE TITLE
Postgres Group By Issue

### ISSUE THREAD

**Issue by ilya-gan** [HealYouDown/flask-statistics#11]
Extension was added based on the instructions.
Request class was added to the model that is already in use.
App runs in docker locally (dev) and in AWS (prod).
psycopg2.errors.GroupingError: column "request.index" must appear in the GROUP BY clause or be used in an aggregate function
LINE 2: FROM (SELECT request.index AS request_index, request.respons...
...
(Background on this error at: https://sqlalche.me/e/14/f405)

**Comment by ilya-gan** [comment]
Full output from teh docker:


my_app_db     | 2021-09-15 18:20:46.800 UTC [129] ERROR:  column "request.index" must appear in the GROUP BY clause or be used in an aggregate function at character 42
my_app_db     | 2021-09-15 18:20:46.800 UTC [129] STATEMENT:  SELECT count(*) AS count_1 
my_app_db     | 	FROM (SELECT request.index AS request_index, request.response_time AS request_response_time, request.date AS request_date, request.method AS request_method, request.size AS request_size, request.status_code AS request_status_code, request.path AS request_path, request.user_agent AS request_user_agent, request.remote_address AS request_remote_address, request.exception AS request_exception, request.referrer AS request_referrer, request.browser AS request_browser, request.platform AS request_platform, request.mimetype AS request_mimetype 
my_app_db     | 	FROM request 
my_app_db     | 	WHERE request.date BETWEEN '2021-09-08T18:20:46.772792'::timestamp AND '2021-09-15T23:59:59.000059'::timestamp GROUP BY request.remote_address) AS anon_1
my_app_web    | [2021-09-15 18:20:46,801] ERROR in app: Exception on /statistics/ [GET]
my_app_web    | Traceback (most recent call last):
my_app_web    |   File "/app/venv/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1772, in _execute_context
my_app_web    |     cursor, statement, parameters, context
my_app_web    |   File "/app/venv/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
my_app_web    |     cursor.execute(statement, parameters)
my_app_web    | psycopg2.errors.GroupingError: column "request.index" must appear in the GROUP BY clause or be used in an aggregate function
my_app_web    | LINE 2: FROM (SELECT request.index AS request_index, request.respons...
my_app_web    |                      ^
my_app_web    | 
my_app_web    | 
my_app_web    | The above exception was the direct cause of the following exception:
my_app_web    | 
my_app_web    | Traceback (most recent call last):
my_app_web    |   File "/app/venv/lib64/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
my_app_web    |     response = self.full_dispatch_request()
my_app_web    |   File "/app/venv/lib64/python3.7/site-packages/sqreen/instrumentation/middlewares/flask_middleware.py", line 31, in wrapper
my_app_web    |     response = wrapped(*args, **kwargs)
my_app_web    |   File "/app/venv/lib64/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
my_app_web    |     rv = self.handle_user_exception(e)
my_app_web    |   File "/app/venv/lib64/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
my_app_web    |     rv = self.dispatch_request()
my_app_web    |   File "/app/venv/lib64/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
my_app_web    |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
my_app_web    |   File "/app/venv/lib64/python3.7/site-packages/flask_statistics/__init__.py", line 93, in index_view
my_app_web    |     end_date)
my_app_web    |   File "/app/venv/lib64/python3.7/site-packages/flask_statistics/utils.py", line 38, in get_number_of_unique_visitors
my_app_web    |     return query.count()
my_app_web    |   File "/app/venv/lib64/python3.7/site-packages/sqlalchemy/orm/query.py", line 3090, in count
my_app_web    |     return self._from_self(col).enable_eagerloads(False).scalar()
my_app_web    |   File "/app/venv/lib64/python3.7/site-packages/sqlalchemy/orm/query.py", line 2831, in scalar
my_app_web    |     ret = self.one()
my_app_web    |   File "/app/venv/lib64/python3.7/site-packages/sqlalchemy/orm/query.py", line 2808, in one
my_app_web    |     return self._iter().one()
my_app_web    |   File "/app/venv/lib64/python3.7/site-packages/sqlalchemy/orm/query.py", line 2849, in _iter
my_app_web    |     execution_options={"_sa_orm_load_options": self.load_options},
my_app_web    |   File "/app/venv/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
my_app_web    |     result = conn._execute_20(statement, params or {}, execution_options)
my_app_web    |   File "/app/venv/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1583, in _execute_20
my_app_web    |     return meth(self, args_10style, kwargs_10style, execution_options)
my_app_web    |   File "/app/venv/lib64/python3.7/site-packages/sqlalchemy/sql/elements.py", line 324, in _execute_on_connection
my_app_web    |     self, multiparams, params, execution_options
my_app_web    |   File "/app/venv/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1462, in _execute_clauseelement
my_app_web    |     cache_hit=cache_hit,
my_app_web    |   File "/app/venv/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1815, in _execute_context
my_app_web    |     e, statement, parameters, cursor, context
my_app_web    |   File "/app/venv/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1996, in _handle_dbapi_exception
my_app_web    |     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
my_app_web    |   File "/app/venv/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
my_app_web    |     raise exception
my_app_web    |   File "/app/venv/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1772, in _execute_context
my_app_web    |     cursor, statement, parameters, context
my_app_web    |   File "/app/venv/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
my_app_web    |     cursor.execute(statement, parameters)
my_app_web    | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.GroupingError) column "request.index" must appear in the GROUP BY clause or be used in an aggregate function
my_app_web    | LINE 2: FROM (SELECT request.index AS request_index, request.respons...
my_app_web    |                      ^
my_app_web    | 
my_app_web    | [SQL: SELECT count(*) AS count_1 
my_app_web    | FROM (SELECT request.index AS request_index, request.response_time AS request_response_time, request.date AS request_date, request.method AS request_method, request.size AS request_size, request.status_code AS request_status_code, request.path AS request_path, request.user_agent AS request_user_agent, request.remote_address AS request_remote_address, request.exception AS request_exception, request.referrer AS request_referrer, request.browser AS request_browser, request.platform AS request_platform, request.mimetype AS request_mimetype 
my_app_web    | FROM request 
my_app_web    | WHERE request.date BETWEEN %(date_1)s AND %(date_2)s GROUP BY request.remote_address) AS anon_1]
my_app_web    | [parameters: {'date_1': datetime.datetime(2021, 9, 8, 18, 20, 46, 772792), 'date_2': datetime.datetime(2021, 9, 15, 23, 59, 59, 59)}]
my_app_web    | (Background on this error at: https://sqlalche.me/e/14/f405)
my_app_web    | SQLALCHEMY_DATABASE_URI: postgresql://user:password@my_app_db:5432/db

**Comment by ilgan** [comment]
Hi @HealYouDown I've opened a PR. I've tried it locally on my Postgres in docker setup, and it worked. Haven't checked on other DBs.

Thank you for your work!
